name: Build and Deploy

on:
  push:
    branches:
      - sources

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the sources branch.
      - name: Checkout Sources Branch
        uses: actions/checkout@v3
        with:
          ref: sources

      # 2. Set up Docker Buildx (optional but recommended)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dimchansky-github-io-builder:latest

      # 5. Build the site (this runs "make build-site" to create the _site folder)
      - name: Build site
        run: make build-site

      # 6. Checkout the master branch into a separate directory (_master).
      - name: Checkout Master Branch
        uses: actions/checkout@v3
        with:
          ref: master
          path: _master

      # 7. Deploy the built site to the master branch.
      - name: Deploy site to Master branch
        run: |
          # Copy the built site into the _master branch folder using rsync
          rsync -av --delete _site/ _master/
          
          cd _master
          
          # Configure git (using GitHub Actions bot identity)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Stage, commit, and push changes (only if there are any changes)
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "Deploy site: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            git push origin master
          else
            echo "No changes to deploy."
          fi